#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='nano'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin
  $path
)

# Make the GNU man pages the default
MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
export MANPATH

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

#
# Misc
#

export FSR="/Users/mattw/Projects/FloSports"
export GPG_TTY=`tty`
export GOPATH="/Users/mattw/Projects/GoCode"
export GATLING_HOME="/Users/mattw/opt/gatling-charts-highcharts-bundle-3.3.1/"
# Add Visual Studio Code (code)
export PATH="${PATH}:/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin"
# export PATH="/usr/local/opt/python/libexec/bin:/Users/mattw/bin:/Users/mattw/Library/Python/3.7/bin:/Volumes/Projects/FloSports/admin-scripts/bin:${PATH}"
export PATH="${PATH}:/Users/mattw/Library/Python/3.7/bin:/Users/mattw/bin"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/mattw/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/mattw/google-cloud-sdk/path.zsh.inc'; fi

##
## Command completion belongs in ~/.zprezto/modules/completion/src
##
