#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

### Customizations ###

# Source custom zsh files
source ~/.zsh/aliases.zsh
source ~/.zsh/functions.zsh
source ~/.zsh/sensitive.zsh

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/mattw/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/mattw/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/mattw/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/mattw/Downloads/google-cloud-sdk/completion.zsh.inc'; fi

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

