#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

### Customizations ###

# Source custom zsh files
source ~/.zsh/aliases.zsh
source ~/.zsh/functions.zsh
source ~/.zsh/sensitive.zsh
